"""dropped column coding_mode

Revision ID: 0febf8c21610
Revises: 4baf7c606f77
Create Date: 2026-02-05 10:00:48.157541

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0febf8c21610'
down_revision: Union[str, Sequence[str], None] = '4baf7c606f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'coding_mode')
    op.add_column('exercise_progress', sa.Column('failed_submissions', sa.INTEGER(), nullable=False))
    op.add_column('exercise_progress', sa.Column('next_grading_allowed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_progress', 'next_grading_allowed_at')
    op.drop_column('exercise_progress', 'failed_submissions')
    op.add_column('exercise', sa.Column('coding_mode', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
