"""add step_limit column to test_case

Revision ID: 2a1b6cce2dae
Revises: fa88dd438b04
Create Date: 2026-02-07 15:51:44.881825

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a1b6cce2dae'
down_revision: Union[str, Sequence[str], None] = 'fa88dd438b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('step_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'step_limit')
    # ### end Alembic commands ###
