"""failed_submissions and next_grading_allowed_at columns added to grading_job table

Revision ID: 3836d6b8e3f6
Revises: 4baf7c606f77
Create Date: 2025-11-09 13:03:28.701620

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3836d6b8e3f6'
down_revision: Union[str, Sequence[str], None] = '4baf7c606f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_progress', sa.Column('skipped', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_progress', 'skipped')
    # ### end Alembic commands ###
