"""testcase table added

Revision ID: 4baf7c606f77
Revises: 9a72ad7167bf
Create Date: 2025-11-06 14:21:18.550847

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4baf7c606f77'
down_revision: Union[str, Sequence[str], None] = '9a72ad7167bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_case',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('precondition', sa.JSON(), nullable=False),
    sa.Column('postcondition', sa.JSON(), nullable=False),
    sa.Column('user_input', sa.JSON(), nullable=False),
    sa.Column('expected_output', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exercise', sa.Column('skip_delay', sa.Integer(), nullable=False))
    op.drop_column('exercise', 'allow_skip_after')
    op.add_column('grading_job', sa.Column('passed', sa.BOOLEAN(), nullable=True))
    op.add_column('grading_job', sa.Column('feedback', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grading_job', 'feedback')
    op.drop_column('grading_job', 'passed')
    op.add_column('exercise', sa.Column('allow_skip_after', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('exercise', 'skip_delay')
    op.drop_table('test_case')
    # ### end Alembic commands ###
