"""add passed and feedback column to GradingJob + add title to TestCase

Revision ID: 53a4dee6ef34
Revises: 9a72ad7167bf
Create Date: 2025-10-09 14:36:41.006723

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a4dee6ef34'
down_revision: Union[str, Sequence[str], None] = '9a72ad7167bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('title', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'title')
    # ### end Alembic commands ###
