"""add markdown_de column to exercise table

Revision ID: 6a76f959a9df
Revises: 2a1b6cce2dae
Create Date: 2026-02-07 16:12:45.015614

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a76f959a9df'
down_revision: Union[str, Sequence[str], None] = '2a1b6cce2dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('markdown_de', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'markdown_de')
    # ### end Alembic commands ###
