"""added expected_instructions column to test_case table

Revision ID: fa88dd438b04
Revises: 0febf8c21610
Create Date: 2026-02-05 10:28:52.171857

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fa88dd438b04'
down_revision: Union[str, Sequence[str], None] = '0febf8c21610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('expected_instructions', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'expected_instructions')
    # ### end Alembic commands ###
